export 'package:flutter/material.dart';
export 'package:patientapp/constants/customroutes.dart';
export 'package:patientapp/constants/colors.dart';
export 'package:patientapp/constants/responsive.dart';
export 'package:patientapp/constants/widgets.dart';
export 'package:patientapp/helpers/routenames.dart';
export 'package:flutter/services.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:patientapp/constants/jsoncontent.dart';